// Generated from tokens/ by tools/codegen/generate.rb.
// Do not edit by hand.
export const materialColorSchemeRoles = [
  "primary",
  "onPrimary",
  "primaryContainer",
  "onPrimaryContainer",
  "inversePrimary",
  "secondary",
  "onSecondary",
  "secondaryContainer",
  "onSecondaryContainer",
  "tertiary",
  "onTertiary",
  "tertiaryContainer",
  "onTertiaryContainer",
  "background",
  "onBackground",
  "surface",
  "onSurface",
  "surfaceVariant",
  "onSurfaceVariant",
  "surfaceTint",
  "inverseSurface",
  "inverseOnSurface",
  "error",
  "onError",
  "errorContainer",
  "onErrorContainer",
  "outline",
  "outlineVariant",
  "scrim",
  "surfaceBright",
  "surfaceContainer",
  "surfaceContainerHigh",
  "surfaceContainerHighest",
  "surfaceContainerLow",
  "surfaceContainerLowest",
  "surfaceDim",
  "primaryFixed",
  "primaryFixedDim",
  "onPrimaryFixed",
  "onPrimaryFixedVariant",
  "secondaryFixed",
  "secondaryFixedDim",
  "onSecondaryFixed",
  "onSecondaryFixedVariant",
  "tertiaryFixed",
  "tertiaryFixedDim",
  "onTertiaryFixed",
  "onTertiaryFixedVariant",
] as const;

export const materialThemePresets = [
  "tonalSpot",
  "fidelity",
  "content",
  "monochrome",
  "neutral",
  "vibrant",
  "expressive",
  "rainbow",
  "fruitSalad",
] as const;

export const materialSourceColor = "#6750A4";

type DeepReadonly<T> = T extends object
  ? { readonly [Key in keyof T]: DeepReadonly<T[Key]> }
  : T;

function deepFreeze<T extends object>(value: T): DeepReadonly<T> {
  for (const nestedValue of Object.values(value)) {
    if (nestedValue !== null && typeof nestedValue === "object") {
      deepFreeze(nestedValue);
    }
  }

  return Object.freeze(value) as DeepReadonly<T>;
}

export const materialThemePresetSourceColors = deepFreeze({
      "tonalSpot": "#6750A4",
      "fidelity": "#6750A4",
      "content": "#6750A4",
      "monochrome": "#6750A4",
      "neutral": "#6750A4",
      "vibrant": "#6750A4",
      "expressive": "#6750A4",
      "rainbow": "#6750A4",
      "fruitSalad": "#6750A4"
    } as const);

export const materialThemePresetKeyColors = deepFreeze({
      "tonalSpot": {
        "primary": "#7E6EA9",
        "secondary": "#7B748A",
        "tertiary": "#996A79",
        "neutral": "#7A767D",
        "neutralVariant": "#7A757F"
      },
      "fidelity": {
        "primary": "#8069BF",
        "secondary": "#7C7296",
        "tertiary": "#C9A74D",
        "neutral": "#7A767D",
        "neutralVariant": "#7A7582"
      },
      "content": {
        "primary": "#8069BF",
        "secondary": "#7C7296",
        "tertiary": "#924274",
        "neutral": "#7A767D",
        "neutralVariant": "#7A7582"
      },
      "monochrome": {
        "primary": "#777777",
        "secondary": "#777777",
        "tertiary": "#777777",
        "neutral": "#777777",
        "neutralVariant": "#777777"
      },
      "neutral": {
        "primary": "#7A7484",
        "secondary": "#7A757F",
        "tertiary": "#7B748A",
        "neutral": "#797678",
        "neutralVariant": "#797678"
      },
      "vibrant": {
        "primary": "#6C0BFF",
        "secondary": "#856F92",
        "tertiary": "#946994",
        "neutral": "#7A7582",
        "neutralVariant": "#7A7484"
      },
      "expressive": {
        "primary": "#1B8672",
        "secondary": "#936B83",
        "tertiary": "#8D6B9B",
        "neutral": "#7C757E",
        "neutralVariant": "#7E7382"
      },
      "rainbow": {
        "primary": "#8069BF",
        "secondary": "#7B748A",
        "tertiary": "#996A79",
        "neutral": "#777777",
        "neutralVariant": "#777777"
      },
      "fruitSalad": {
        "primary": "#247CBB",
        "secondary": "#4B7BA7",
        "tertiary": "#7E6EA9",
        "neutral": "#7A7582",
        "neutralVariant": "#7B748A"
      }
    } as const);

export const materialThemePresetSchemes = deepFreeze({
      "tonalSpot": {
        "light": {
          "primary": "#65558F",
          "onPrimary": "#FFFFFF",
          "primaryContainer": "#E9DDFF",
          "onPrimaryContainer": "#4D3D75",
          "inversePrimary": "#CFBDFE",
          "secondary": "#625B71",
          "onSecondary": "#FFFFFF",
          "secondaryContainer": "#E8DEF8",
          "onSecondaryContainer": "#4A4458",
          "tertiary": "#7E5260",
          "onTertiary": "#FFFFFF",
          "tertiaryContainer": "#FFD9E3",
          "onTertiaryContainer": "#633B48",
          "background": "#FDF7FF",
          "onBackground": "#1D1B20",
          "surface": "#FDF7FF",
          "onSurface": "#1D1B20",
          "surfaceVariant": "#E7E0EB",
          "onSurfaceVariant": "#49454E",
          "surfaceTint": "#65558F",
          "inverseSurface": "#322F35",
          "inverseOnSurface": "#F5EFF7",
          "error": "#BA1A1A",
          "onError": "#FFFFFF",
          "errorContainer": "#FFDAD6",
          "onErrorContainer": "#93000A",
          "outline": "#7A757F",
          "outlineVariant": "#CAC4CF",
          "scrim": "#000000",
          "surfaceBright": "#FDF7FF",
          "surfaceContainer": "#F2ECF4",
          "surfaceContainerHigh": "#ECE6EE",
          "surfaceContainerHighest": "#E6E0E9",
          "surfaceContainerLow": "#F8F2FA",
          "surfaceContainerLowest": "#FFFFFF",
          "surfaceDim": "#DED8E0",
          "primaryFixed": "#E9DDFF",
          "primaryFixedDim": "#CFBDFE",
          "onPrimaryFixed": "#201047",
          "onPrimaryFixedVariant": "#4D3D75",
          "secondaryFixed": "#E8DEF8",
          "secondaryFixedDim": "#CBC2DB",
          "onSecondaryFixed": "#1E192B",
          "onSecondaryFixedVariant": "#4A4458",
          "tertiaryFixed": "#FFD9E3",
          "tertiaryFixedDim": "#EFB8C8",
          "onTertiaryFixed": "#31101D",
          "onTertiaryFixedVariant": "#633B48"
        },
        "dark": {
          "primary": "#CFBDFE",
          "onPrimary": "#36275D",
          "primaryContainer": "#4D3D75",
          "onPrimaryContainer": "#E9DDFF",
          "inversePrimary": "#65558F",
          "secondary": "#CBC2DB",
          "onSecondary": "#332D41",
          "secondaryContainer": "#4A4458",
          "onSecondaryContainer": "#E8DEF8",
          "tertiary": "#EFB8C8",
          "onTertiary": "#4A2532",
          "tertiaryContainer": "#633B48",
          "onTertiaryContainer": "#FFD9E3",
          "background": "#141218",
          "onBackground": "#E6E0E9",
          "surface": "#141218",
          "onSurface": "#E6E0E9",
          "surfaceVariant": "#49454E",
          "onSurfaceVariant": "#CAC4CF",
          "surfaceTint": "#CFBDFE",
          "inverseSurface": "#E6E0E9",
          "inverseOnSurface": "#322F35",
          "error": "#FFB4AB",
          "onError": "#690005",
          "errorContainer": "#93000A",
          "onErrorContainer": "#FFDAD6",
          "outline": "#948F99",
          "outlineVariant": "#49454E",
          "scrim": "#000000",
          "surfaceBright": "#3B383E",
          "surfaceContainer": "#211F24",
          "surfaceContainerHigh": "#2B292F",
          "surfaceContainerHighest": "#36343A",
          "surfaceContainerLow": "#1D1B20",
          "surfaceContainerLowest": "#0F0D13",
          "surfaceDim": "#141218",
          "primaryFixed": "#E9DDFF",
          "primaryFixedDim": "#CFBDFE",
          "onPrimaryFixed": "#201047",
          "onPrimaryFixedVariant": "#4D3D75",
          "secondaryFixed": "#E8DEF8",
          "secondaryFixedDim": "#CBC2DB",
          "onSecondaryFixed": "#1E192B",
          "onSecondaryFixedVariant": "#4A4458",
          "tertiaryFixed": "#FFD9E3",
          "tertiaryFixedDim": "#EFB8C8",
          "onTertiaryFixed": "#31101D",
          "onTertiaryFixedVariant": "#633B48"
        }
      },
      "fidelity": {
        "light": {
          "primary": "#4F378A",
          "onPrimary": "#FFFFFF",
          "primaryContainer": "#6750A4",
          "onPrimaryContainer": "#E0D2FF",
          "inversePrimary": "#CFBCFF",
          "secondary": "#63597C",
          "onSecondary": "#FFFFFF",
          "secondaryContainer": "#E1D4FD",
          "onSecondaryContainer": "#645A7D",
          "tertiary": "#765B00",
          "onTertiary": "#FFFFFF",
          "tertiaryContainer": "#C9A74D",
          "onTertiaryContainer": "#503D00",
          "background": "#FDF7FF",
          "onBackground": "#1D1B20",
          "surface": "#FDF7FF",
          "onSurface": "#1D1B20",
          "surfaceVariant": "#E7E0EE",
          "onSurfaceVariant": "#494551",
          "surfaceTint": "#6750A4",
          "inverseSurface": "#322F35",
          "inverseOnSurface": "#F5EFF7",
          "error": "#BA1A1A",
          "onError": "#FFFFFF",
          "errorContainer": "#FFDAD6",
          "onErrorContainer": "#93000A",
          "outline": "#7A7582",
          "outlineVariant": "#CBC4D2",
          "scrim": "#000000",
          "surfaceBright": "#FDF7FF",
          "surfaceContainer": "#F2ECF4",
          "surfaceContainerHigh": "#ECE6EE",
          "surfaceContainerHighest": "#E6E0E9",
          "surfaceContainerLow": "#F8F2FA",
          "surfaceContainerLowest": "#FFFFFF",
          "surfaceDim": "#DED8E0",
          "primaryFixed": "#E9DDFF",
          "primaryFixedDim": "#CFBCFF",
          "onPrimaryFixed": "#22005D",
          "onPrimaryFixedVariant": "#4F378A",
          "secondaryFixed": "#E9DDFF",
          "secondaryFixedDim": "#CDC0E9",
          "onSecondaryFixed": "#1F1635",
          "onSecondaryFixedVariant": "#4B4263",
          "tertiaryFixed": "#FFDF93",
          "tertiaryFixedDim": "#E7C365",
          "onTertiaryFixed": "#241A00",
          "onTertiaryFixedVariant": "#594400"
        },
        "dark": {
          "primary": "#CFBCFF",
          "onPrimary": "#381E72",
          "primaryContainer": "#6750A4",
          "onPrimaryContainer": "#E0D2FF",
          "inversePrimary": "#6750A4",
          "secondary": "#CDC0E9",
          "onSecondary": "#342B4B",
          "secondaryContainer": "#4D4465",
          "onSecondaryContainer": "#BFB2DA",
          "tertiary": "#E7C365",
          "onTertiary": "#3E2E00",
          "tertiaryContainer": "#C9A74D",
          "onTertiaryContainer": "#503D00",
          "background": "#141218",
          "onBackground": "#E6E0E9",
          "surface": "#141218",
          "onSurface": "#E6E0E9",
          "surfaceVariant": "#494551",
          "onSurfaceVariant": "#CBC4D2",
          "surfaceTint": "#CFBCFF",
          "inverseSurface": "#E6E0E9",
          "inverseOnSurface": "#322F35",
          "error": "#FFB4AB",
          "onError": "#690005",
          "errorContainer": "#93000A",
          "onErrorContainer": "#FFDAD6",
          "outline": "#948E9C",
          "outlineVariant": "#494551",
          "scrim": "#000000",
          "surfaceBright": "#3B383E",
          "surfaceContainer": "#211F24",
          "surfaceContainerHigh": "#2B292F",
          "surfaceContainerHighest": "#36343A",
          "surfaceContainerLow": "#1D1B20",
          "surfaceContainerLowest": "#0F0D13",
          "surfaceDim": "#141218",
          "primaryFixed": "#E9DDFF",
          "primaryFixedDim": "#CFBCFF",
          "onPrimaryFixed": "#22005D",
          "onPrimaryFixedVariant": "#4F378A",
          "secondaryFixed": "#E9DDFF",
          "secondaryFixedDim": "#CDC0E9",
          "onSecondaryFixed": "#1F1635",
          "onSecondaryFixedVariant": "#4B4263",
          "tertiaryFixed": "#FFDF93",
          "tertiaryFixedDim": "#E7C365",
          "onTertiaryFixed": "#241A00",
          "onTertiaryFixedVariant": "#594400"
        }
      },
      "content": {
        "light": {
          "primary": "#4F378A",
          "onPrimary": "#FFFFFF",
          "primaryContainer": "#6750A4",
          "onPrimaryContainer": "#E0D2FF",
          "inversePrimary": "#CFBCFF",
          "secondary": "#63597C",
          "onSecondary": "#FFFFFF",
          "secondaryContainer": "#E1D4FD",
          "onSecondaryContainer": "#645A7D",
          "tertiary": "#762A5B",
          "onTertiary": "#FFFFFF",
          "tertiaryContainer": "#924274",
          "onTertiaryContainer": "#FFCAE5",
          "background": "#FDF7FF",
          "onBackground": "#1D1B20",
          "surface": "#FDF7FF",
          "onSurface": "#1D1B20",
          "surfaceVariant": "#E7E0EE",
          "onSurfaceVariant": "#494551",
          "surfaceTint": "#6750A4",
          "inverseSurface": "#322F35",
          "inverseOnSurface": "#F5EFF7",
          "error": "#BA1A1A",
          "onError": "#FFFFFF",
          "errorContainer": "#FFDAD6",
          "onErrorContainer": "#93000A",
          "outline": "#7A7582",
          "outlineVariant": "#CBC4D2",
          "scrim": "#000000",
          "surfaceBright": "#FDF7FF",
          "surfaceContainer": "#F2ECF4",
          "surfaceContainerHigh": "#ECE6EE",
          "surfaceContainerHighest": "#E6E0E9",
          "surfaceContainerLow": "#F8F2FA",
          "surfaceContainerLowest": "#FFFFFF",
          "surfaceDim": "#DED8E0",
          "primaryFixed": "#E9DDFF",
          "primaryFixedDim": "#CFBCFF",
          "onPrimaryFixed": "#22005D",
          "onPrimaryFixedVariant": "#4F378A",
          "secondaryFixed": "#E9DDFF",
          "secondaryFixedDim": "#CDC0E9",
          "onSecondaryFixed": "#1F1635",
          "onSecondaryFixedVariant": "#4B4263",
          "tertiaryFixed": "#FFD8EA",
          "tertiaryFixedDim": "#FFAEDB",
          "onTertiaryFixed": "#3C002B",
          "onTertiaryFixedVariant": "#752A5B"
        },
        "dark": {
          "primary": "#CFBCFF",
          "onPrimary": "#381E72",
          "primaryContainer": "#6750A4",
          "onPrimaryContainer": "#E0D2FF",
          "inversePrimary": "#6750A4",
          "secondary": "#CDC0E9",
          "onSecondary": "#342B4B",
          "secondaryContainer": "#4D4465",
          "onSecondaryContainer": "#BFB2DA",
          "tertiary": "#FFAEDB",
          "onTertiary": "#5A1243",
          "tertiaryContainer": "#924274",
          "onTertiaryContainer": "#FFCAE5",
          "background": "#141218",
          "onBackground": "#E6E0E9",
          "surface": "#141218",
          "onSurface": "#E6E0E9",
          "surfaceVariant": "#494551",
          "onSurfaceVariant": "#CBC4D2",
          "surfaceTint": "#CFBCFF",
          "inverseSurface": "#E6E0E9",
          "inverseOnSurface": "#322F35",
          "error": "#FFB4AB",
          "onError": "#690005",
          "errorContainer": "#93000A",
          "onErrorContainer": "#FFDAD6",
          "outline": "#948E9C",
          "outlineVariant": "#494551",
          "scrim": "#000000",
          "surfaceBright": "#3B383E",
          "surfaceContainer": "#211F24",
          "surfaceContainerHigh": "#2B292F",
          "surfaceContainerHighest": "#36343A",
          "surfaceContainerLow": "#1D1B20",
          "surfaceContainerLowest": "#0F0D13",
          "surfaceDim": "#141218",
          "primaryFixed": "#E9DDFF",
          "primaryFixedDim": "#CFBCFF",
          "onPrimaryFixed": "#22005D",
          "onPrimaryFixedVariant": "#4F378A",
          "secondaryFixed": "#E9DDFF",
          "secondaryFixedDim": "#CDC0E9",
          "onSecondaryFixed": "#1F1635",
          "onSecondaryFixedVariant": "#4B4263",
          "tertiaryFixed": "#FFD8EA",
          "tertiaryFixedDim": "#FFAEDB",
          "onTertiaryFixed": "#3C002B",
          "onTertiaryFixedVariant": "#752A5B"
        }
      },
      "monochrome": {
        "light": {
          "primary": "#000000",
          "onPrimary": "#E2E2E2",
          "primaryContainer": "#3B3B3B",
          "onPrimaryContainer": "#FFFFFF",
          "inversePrimary": "#C6C6C6",
          "secondary": "#5E5E5E",
          "onSecondary": "#FFFFFF",
          "secondaryContainer": "#D4D4D4",
          "onSecondaryContainer": "#1B1B1B",
          "tertiary": "#3B3B3B",
          "onTertiary": "#E2E2E2",
          "tertiaryContainer": "#747474",
          "onTertiaryContainer": "#FFFFFF",
          "background": "#F9F9F9",
          "onBackground": "#1B1B1B",
          "surface": "#F9F9F9",
          "onSurface": "#1B1B1B",
          "surfaceVariant": "#E2E2E2",
          "onSurfaceVariant": "#474747",
          "surfaceTint": "#5E5E5E",
          "inverseSurface": "#303030",
          "inverseOnSurface": "#F1F1F1",
          "error": "#BA1A1A",
          "onError": "#FFFFFF",
          "errorContainer": "#FFDAD6",
          "onErrorContainer": "#410002",
          "outline": "#777777",
          "outlineVariant": "#C6C6C6",
          "scrim": "#000000",
          "surfaceBright": "#F9F9F9",
          "surfaceContainer": "#EEEEEE",
          "surfaceContainerHigh": "#E8E8E8",
          "surfaceContainerHighest": "#E2E2E2",
          "surfaceContainerLow": "#F3F3F3",
          "surfaceContainerLowest": "#FFFFFF",
          "surfaceDim": "#DADADA",
          "primaryFixed": "#5E5E5E",
          "primaryFixedDim": "#474747",
          "onPrimaryFixed": "#FFFFFF",
          "onPrimaryFixedVariant": "#E2E2E2",
          "secondaryFixed": "#C6C6C6",
          "secondaryFixedDim": "#ABABAB",
          "onSecondaryFixed": "#1B1B1B",
          "onSecondaryFixedVariant": "#3B3B3B",
          "tertiaryFixed": "#5E5E5E",
          "tertiaryFixedDim": "#474747",
          "onTertiaryFixed": "#FFFFFF",
          "onTertiaryFixedVariant": "#E2E2E2"
        },
        "dark": {
          "primary": "#FFFFFF",
          "onPrimary": "#1B1B1B",
          "primaryContainer": "#D4D4D4",
          "onPrimaryContainer": "#000000",
          "inversePrimary": "#5E5E5E",
          "secondary": "#C6C6C6",
          "onSecondary": "#1B1B1B",
          "secondaryContainer": "#474747",
          "onSecondaryContainer": "#E2E2E2",
          "tertiary": "#E2E2E2",
          "onTertiary": "#1B1B1B",
          "tertiaryContainer": "#919191",
          "onTertiaryContainer": "#000000",
          "background": "#131313",
          "onBackground": "#E2E2E2",
          "surface": "#131313",
          "onSurface": "#E2E2E2",
          "surfaceVariant": "#474747",
          "onSurfaceVariant": "#C6C6C6",
          "surfaceTint": "#C6C6C6",
          "inverseSurface": "#E2E2E2",
          "inverseOnSurface": "#303030",
          "error": "#FFB4AB",
          "onError": "#690005",
          "errorContainer": "#93000A",
          "onErrorContainer": "#FFDAD6",
          "outline": "#919191",
          "outlineVariant": "#474747",
          "scrim": "#000000",
          "surfaceBright": "#393939",
          "surfaceContainer": "#1F1F1F",
          "surfaceContainerHigh": "#2A2A2A",
          "surfaceContainerHighest": "#353535",
          "surfaceContainerLow": "#1B1B1B",
          "surfaceContainerLowest": "#0E0E0E",
          "surfaceDim": "#131313",
          "primaryFixed": "#5E5E5E",
          "primaryFixedDim": "#474747",
          "onPrimaryFixed": "#FFFFFF",
          "onPrimaryFixedVariant": "#E2E2E2",
          "secondaryFixed": "#C6C6C6",
          "secondaryFixedDim": "#ABABAB",
          "onSecondaryFixed": "#1B1B1B",
          "onSecondaryFixedVariant": "#3B3B3B",
          "tertiaryFixed": "#5E5E5E",
          "tertiaryFixedDim": "#474747",
          "onTertiaryFixed": "#FFFFFF",
          "onTertiaryFixedVariant": "#E2E2E2"
        }
      },
      "neutral": {
        "light": {
          "primary": "#615C6B",
          "onPrimary": "#FFFFFF",
          "primaryContainer": "#E7DFF2",
          "onPrimaryContainer": "#494453",
          "inversePrimary": "#CBC3D5",
          "secondary": "#615D66",
          "onSecondary": "#FFFFFF",
          "secondaryContainer": "#E7E0EB",
          "onSecondaryContainer": "#49454E",
          "tertiary": "#625B71",
          "onTertiary": "#FFFFFF",
          "tertiaryContainer": "#E8DEF8",
          "onTertiaryContainer": "#4A4458",
          "background": "#FDF8FA",
          "onBackground": "#1C1B1D",
          "surface": "#FDF8FA",
          "onSurface": "#1C1B1D",
          "surfaceVariant": "#E6E1E3",
          "onSurfaceVariant": "#484648",
          "surfaceTint": "#615C6B",
          "inverseSurface": "#313032",
          "inverseOnSurface": "#F4EFF1",
          "error": "#BA1A1A",
          "onError": "#FFFFFF",
          "errorContainer": "#FFDAD6",
          "onErrorContainer": "#93000A",
          "outline": "#797678",
          "outlineVariant": "#C9C5C7",
          "scrim": "#000000",
          "surfaceBright": "#FDF8FA",
          "surfaceContainer": "#F1EDEE",
          "surfaceContainerHigh": "#EBE7E9",
          "surfaceContainerHighest": "#E6E1E3",
          "surfaceContainerLow": "#F7F2F4",
          "surfaceContainerLowest": "#FFFFFF",
          "surfaceDim": "#DDD9DB",
          "primaryFixed": "#E7DFF2",
          "primaryFixedDim": "#CBC3D5",
          "onPrimaryFixed": "#1D1A26",
          "onPrimaryFixedVariant": "#494453",
          "secondaryFixed": "#E7E0EB",
          "secondaryFixedDim": "#CAC4CF",
          "onSecondaryFixed": "#1D1A22",
          "onSecondaryFixedVariant": "#49454E",
          "tertiaryFixed": "#E8DEF8",
          "tertiaryFixedDim": "#CBC2DB",
          "onTertiaryFixed": "#1E192B",
          "onTertiaryFixedVariant": "#4A4458"
        },
        "dark": {
          "primary": "#CBC3D5",
          "onPrimary": "#322E3C",
          "primaryContainer": "#494453",
          "onPrimaryContainer": "#E7DFF2",
          "inversePrimary": "#615C6B",
          "secondary": "#CAC4CF",
          "onSecondary": "#322F38",
          "secondaryContainer": "#49454E",
          "onSecondaryContainer": "#E7E0EB",
          "tertiary": "#CBC2DB",
          "onTertiary": "#332D41",
          "tertiaryContainer": "#4A4458",
          "onTertiaryContainer": "#E8DEF8",
          "background": "#141314",
          "onBackground": "#E6E1E3",
          "surface": "#141314",
          "onSurface": "#E6E1E3",
          "surfaceVariant": "#484648",
          "onSurfaceVariant": "#C9C5C7",
          "surfaceTint": "#CBC3D5",
          "inverseSurface": "#E6E1E3",
          "inverseOnSurface": "#313032",
          "error": "#FFB4AB",
          "onError": "#690005",
          "errorContainer": "#93000A",
          "onErrorContainer": "#FFDAD6",
          "outline": "#939092",
          "outlineVariant": "#484648",
          "scrim": "#000000",
          "surfaceBright": "#3A393A",
          "surfaceContainer": "#201F21",
          "surfaceContainerHigh": "#2B292B",
          "surfaceContainerHighest": "#363436",
          "surfaceContainerLow": "#1C1B1D",
          "surfaceContainerLowest": "#0F0E0F",
          "surfaceDim": "#141314",
          "primaryFixed": "#E7DFF2",
          "primaryFixedDim": "#CBC3D5",
          "onPrimaryFixed": "#1D1A26",
          "onPrimaryFixedVariant": "#494453",
          "secondaryFixed": "#E7E0EB",
          "secondaryFixedDim": "#CAC4CF",
          "onSecondaryFixed": "#1D1A22",
          "onSecondaryFixedVariant": "#49454E",
          "tertiaryFixed": "#E8DEF8",
          "tertiaryFixedDim": "#CBC2DB",
          "onTertiaryFixed": "#1E192B",
          "onTertiaryFixedVariant": "#4A4458"
        }
      },
      "vibrant": {
        "light": {
          "primary": "#6F19FF",
          "onPrimary": "#FFFFFF",
          "primaryContainer": "#E9DDFF",
          "onPrimaryContainer": "#5400CC",
          "inversePrimary": "#CFBCFF",
          "secondary": "#6B5778",
          "onSecondary": "#FFFFFF",
          "secondaryContainer": "#F3DAFF",
          "onSecondaryContainer": "#523F5F",
          "tertiary": "#79507A",
          "onTertiary": "#FFFFFF",
          "tertiaryContainer": "#FFD6FC",
          "onTertiaryContainer": "#5F3961",
          "background": "#FDF7FF",
          "onBackground": "#1D1A24",
          "surface": "#FDF7FF",
          "onSurface": "#1D1A24",
          "surfaceVariant": "#E7DFF2",
          "onSurfaceVariant": "#494453",
          "surfaceTint": "#6F19FF",
          "inverseSurface": "#322F3A",
          "inverseOnSurface": "#F5EEFD",
          "error": "#BA1A1A",
          "onError": "#FFFFFF",
          "errorContainer": "#FFDAD6",
          "onErrorContainer": "#93000A",
          "outline": "#7A7484",
          "outlineVariant": "#CBC3D5",
          "scrim": "#000000",
          "surfaceBright": "#FDF7FF",
          "surfaceContainer": "#F2EBFA",
          "surfaceContainerHigh": "#EDE5F4",
          "surfaceContainerHighest": "#E7E0EF",
          "surfaceContainerLow": "#F8F1FF",
          "surfaceContainerLowest": "#FFFFFF",
          "surfaceDim": "#DED7E6",
          "primaryFixed": "#E9DDFF",
          "primaryFixedDim": "#CFBCFF",
          "onPrimaryFixed": "#22005D",
          "onPrimaryFixedVariant": "#5400CC",
          "secondaryFixed": "#F3DAFF",
          "secondaryFixedDim": "#D7BEE4",
          "onSecondaryFixed": "#251431",
          "onSecondaryFixedVariant": "#523F5F",
          "tertiaryFixed": "#FFD6FC",
          "tertiaryFixedDim": "#E8B7E7",
          "onTertiaryFixed": "#2F0D33",
          "onTertiaryFixedVariant": "#5F3961"
        },
        "dark": {
          "primary": "#CFBCFF",
          "onPrimary": "#3A0092",
          "primaryContainer": "#5400CC",
          "onPrimaryContainer": "#E9DDFF",
          "inversePrimary": "#6F19FF",
          "secondary": "#D7BEE4",
          "onSecondary": "#3B2948",
          "secondaryContainer": "#523F5F",
          "onSecondaryContainer": "#F3DAFF",
          "tertiary": "#E8B7E7",
          "onTertiary": "#462349",
          "tertiaryContainer": "#5F3961",
          "onTertiaryContainer": "#FFD6FC",
          "background": "#15121C",
          "onBackground": "#E7E0EF",
          "surface": "#15121C",
          "onSurface": "#E7E0EF",
          "surfaceVariant": "#494453",
          "onSurfaceVariant": "#CBC3D5",
          "surfaceTint": "#CFBCFF",
          "inverseSurface": "#E7E0EF",
          "inverseOnSurface": "#322F3A",
          "error": "#FFB4AB",
          "onError": "#690005",
          "errorContainer": "#93000A",
          "onErrorContainer": "#FFDAD6",
          "outline": "#948E9F",
          "outlineVariant": "#494453",
          "scrim": "#000000",
          "surfaceBright": "#3B3743",
          "surfaceContainer": "#211E28",
          "surfaceContainerHigh": "#2C2833",
          "surfaceContainerHighest": "#37333E",
          "surfaceContainerLow": "#1D1A24",
          "surfaceContainerLowest": "#0F0D16",
          "surfaceDim": "#15121C",
          "primaryFixed": "#E9DDFF",
          "primaryFixedDim": "#CFBCFF",
          "onPrimaryFixed": "#22005D",
          "onPrimaryFixedVariant": "#5400CC",
          "secondaryFixed": "#F3DAFF",
          "secondaryFixedDim": "#D7BEE4",
          "onSecondaryFixed": "#251431",
          "onSecondaryFixedVariant": "#523F5F",
          "tertiaryFixed": "#FFD6FC",
          "tertiaryFixedDim": "#E8B7E7",
          "onTertiaryFixed": "#2F0D33",
          "onTertiaryFixedVariant": "#5F3961"
        }
      },
      "expressive": {
        "light": {
          "primary": "#006B5A",
          "onPrimary": "#FFFFFF",
          "primaryContainer": "#95F4DC",
          "onPrimaryContainer": "#005143",
          "inversePrimary": "#79D7C0",
          "secondary": "#79536A",
          "onSecondary": "#FFFFFF",
          "secondaryContainer": "#FFD8ED",
          "onSecondaryContainer": "#5F3C52",
          "tertiary": "#735280",
          "onTertiary": "#FFFFFF",
          "tertiaryContainer": "#F7D8FF",
          "onTertiaryContainer": "#593B67",
          "background": "#FFF7FD",
          "onBackground": "#1F1A21",
          "surface": "#FFF7FD",
          "onSurface": "#1F1A21",
          "surfaceVariant": "#ECDEF0",
          "onSurfaceVariant": "#4D4351",
          "surfaceTint": "#006B5A",
          "inverseSurface": "#342E37",
          "inverseOnSurface": "#F8EDF9",
          "error": "#BA1A1A",
          "onError": "#FFFFFF",
          "errorContainer": "#FFDAD6",
          "onErrorContainer": "#93000A",
          "outline": "#7E7383",
          "outlineVariant": "#CFC2D3",
          "scrim": "#000000",
          "surfaceBright": "#FFF7FD",
          "surfaceContainer": "#F5EBF6",
          "surfaceContainerHigh": "#EFE5F0",
          "surfaceContainerHighest": "#EADFEA",
          "surfaceContainerLow": "#FBF0FB",
          "surfaceContainerLowest": "#FFFFFF",
          "surfaceDim": "#E1D7E2",
          "primaryFixed": "#95F4DC",
          "primaryFixedDim": "#79D7C0",
          "onPrimaryFixed": "#00201A",
          "onPrimaryFixedVariant": "#005143",
          "secondaryFixed": "#FFD8ED",
          "secondaryFixedDim": "#E8B9D4",
          "onSecondaryFixed": "#2E1125",
          "onSecondaryFixedVariant": "#5F3C52",
          "tertiaryFixed": "#F7D8FF",
          "tertiaryFixedDim": "#E0B9EE",
          "onTertiaryFixed": "#2B0E39",
          "onTertiaryFixedVariant": "#593B67"
        },
        "dark": {
          "primary": "#79D7C0",
          "onPrimary": "#00382E",
          "primaryContainer": "#005143",
          "onPrimaryContainer": "#95F4DC",
          "inversePrimary": "#006B5A",
          "secondary": "#E8B9D4",
          "onSecondary": "#46263B",
          "secondaryContainer": "#5F3C52",
          "onSecondaryContainer": "#FFD8ED",
          "tertiary": "#E0B9EE",
          "onTertiary": "#41244F",
          "tertiaryContainer": "#593B67",
          "onTertiaryContainer": "#F7D8FF",
          "background": "#161219",
          "onBackground": "#EADFEA",
          "surface": "#161219",
          "onSurface": "#EADFEA",
          "surfaceVariant": "#4D4351",
          "onSurfaceVariant": "#CFC2D3",
          "surfaceTint": "#79D7C0",
          "inverseSurface": "#EADFEA",
          "inverseOnSurface": "#342E37",
          "error": "#FFB4AB",
          "onError": "#690005",
          "errorContainer": "#93000A",
          "onErrorContainer": "#FFDAD6",
          "outline": "#988D9D",
          "outlineVariant": "#4D4351",
          "scrim": "#000000",
          "surfaceBright": "#3D373F",
          "surfaceContainer": "#231E25",
          "surfaceContainerHigh": "#2D2830",
          "surfaceContainerHighest": "#38333B",
          "surfaceContainerLow": "#1F1A21",
          "surfaceContainerLowest": "#110D14",
          "surfaceDim": "#161219",
          "primaryFixed": "#95F4DC",
          "primaryFixedDim": "#79D7C0",
          "onPrimaryFixed": "#00201A",
          "onPrimaryFixedVariant": "#005143",
          "secondaryFixed": "#FFD8ED",
          "secondaryFixedDim": "#E8B9D4",
          "onSecondaryFixed": "#2E1125",
          "onSecondaryFixedVariant": "#5F3C52",
          "tertiaryFixed": "#F7D8FF",
          "tertiaryFixedDim": "#E0B9EE",
          "onTertiaryFixed": "#2B0E39",
          "onTertiaryFixedVariant": "#593B67"
        }
      },
      "rainbow": {
        "light": {
          "primary": "#6750A4",
          "onPrimary": "#FFFFFF",
          "primaryContainer": "#E9DDFF",
          "onPrimaryContainer": "#4F378A",
          "inversePrimary": "#CFBCFF",
          "secondary": "#625B71",
          "onSecondary": "#FFFFFF",
          "secondaryContainer": "#E8DEF8",
          "onSecondaryContainer": "#4A4458",
          "tertiary": "#7E5260",
          "onTertiary": "#FFFFFF",
          "tertiaryContainer": "#FFD9E3",
          "onTertiaryContainer": "#633B48",
          "background": "#F9F9F9",
          "onBackground": "#1B1B1B",
          "surface": "#F9F9F9",
          "onSurface": "#1B1B1B",
          "surfaceVariant": "#E2E2E2",
          "onSurfaceVariant": "#474747",
          "surfaceTint": "#6750A4",
          "inverseSurface": "#303030",
          "inverseOnSurface": "#F1F1F1",
          "error": "#BA1A1A",
          "onError": "#FFFFFF",
          "errorContainer": "#FFDAD6",
          "onErrorContainer": "#93000A",
          "outline": "#777777",
          "outlineVariant": "#C6C6C6",
          "scrim": "#000000",
          "surfaceBright": "#F9F9F9",
          "surfaceContainer": "#EEEEEE",
          "surfaceContainerHigh": "#E8E8E8",
          "surfaceContainerHighest": "#E2E2E2",
          "surfaceContainerLow": "#F3F3F3",
          "surfaceContainerLowest": "#FFFFFF",
          "surfaceDim": "#DADADA",
          "primaryFixed": "#E9DDFF",
          "primaryFixedDim": "#CFBCFF",
          "onPrimaryFixed": "#22005D",
          "onPrimaryFixedVariant": "#4F378A",
          "secondaryFixed": "#E8DEF8",
          "secondaryFixedDim": "#CBC2DB",
          "onSecondaryFixed": "#1E192B",
          "onSecondaryFixedVariant": "#4A4458",
          "tertiaryFixed": "#FFD9E3",
          "tertiaryFixedDim": "#EFB8C8",
          "onTertiaryFixed": "#31101D",
          "onTertiaryFixedVariant": "#633B48"
        },
        "dark": {
          "primary": "#CFBCFF",
          "onPrimary": "#381E72",
          "primaryContainer": "#4F378A",
          "onPrimaryContainer": "#E9DDFF",
          "inversePrimary": "#6750A4",
          "secondary": "#CBC2DB",
          "onSecondary": "#332D41",
          "secondaryContainer": "#4A4458",
          "onSecondaryContainer": "#E8DEF8",
          "tertiary": "#EFB8C8",
          "onTertiary": "#4A2532",
          "tertiaryContainer": "#633B48",
          "onTertiaryContainer": "#FFD9E3",
          "background": "#131313",
          "onBackground": "#E2E2E2",
          "surface": "#131313",
          "onSurface": "#E2E2E2",
          "surfaceVariant": "#474747",
          "onSurfaceVariant": "#C6C6C6",
          "surfaceTint": "#CFBCFF",
          "inverseSurface": "#E2E2E2",
          "inverseOnSurface": "#303030",
          "error": "#FFB4AB",
          "onError": "#690005",
          "errorContainer": "#93000A",
          "onErrorContainer": "#FFDAD6",
          "outline": "#919191",
          "outlineVariant": "#474747",
          "scrim": "#000000",
          "surfaceBright": "#393939",
          "surfaceContainer": "#1F1F1F",
          "surfaceContainerHigh": "#2A2A2A",
          "surfaceContainerHighest": "#353535",
          "surfaceContainerLow": "#1B1B1B",
          "surfaceContainerLowest": "#0E0E0E",
          "surfaceDim": "#131313",
          "primaryFixed": "#E9DDFF",
          "primaryFixedDim": "#CFBCFF",
          "onPrimaryFixed": "#22005D",
          "onPrimaryFixedVariant": "#4F378A",
          "secondaryFixed": "#E8DEF8",
          "secondaryFixedDim": "#CBC2DB",
          "onSecondaryFixed": "#1E192B",
          "onSecondaryFixedVariant": "#4A4458",
          "tertiaryFixed": "#FFD9E3",
          "tertiaryFixedDim": "#EFB8C8",
          "onTertiaryFixed": "#31101D",
          "onTertiaryFixedVariant": "#633B48"
        }
      },
      "fruitSalad": {
        "light": {
          "primary": "#00639C",
          "onPrimary": "#FFFFFF",
          "primaryContainer": "#CEE5FF",
          "onPrimaryContainer": "#004A77",
          "inversePrimary": "#97CBFF",
          "secondary": "#30628C",
          "onSecondary": "#FFFFFF",
          "secondaryContainer": "#CEE5FF",
          "onSecondaryContainer": "#104A73",
          "tertiary": "#65558F",
          "onTertiary": "#FFFFFF",
          "tertiaryContainer": "#E9DDFF",
          "onTertiaryContainer": "#4D3D75",
          "background": "#FDF7FF",
          "onBackground": "#1D1A24",
          "surface": "#FDF7FF",
          "onSurface": "#1D1A24",
          "surfaceVariant": "#E8DEF8",
          "onSurfaceVariant": "#4A4458",
          "surfaceTint": "#00639C",
          "inverseSurface": "#322F3A",
          "inverseOnSurface": "#F5EEFD",
          "error": "#BA1A1A",
          "onError": "#FFFFFF",
          "errorContainer": "#FFDAD6",
          "onErrorContainer": "#93000A",
          "outline": "#7B748A",
          "outlineVariant": "#CBC2DB",
          "scrim": "#000000",
          "surfaceBright": "#FDF7FF",
          "surfaceContainer": "#F2EBFA",
          "surfaceContainerHigh": "#EDE5F4",
          "surfaceContainerHighest": "#E7E0EF",
          "surfaceContainerLow": "#F8F1FF",
          "surfaceContainerLowest": "#FFFFFF",
          "surfaceDim": "#DED7E6",
          "primaryFixed": "#CEE5FF",
          "primaryFixedDim": "#97CBFF",
          "onPrimaryFixed": "#001D33",
          "onPrimaryFixedVariant": "#004A77",
          "secondaryFixed": "#CEE5FF",
          "secondaryFixedDim": "#9CCBFB",
          "onSecondaryFixed": "#001D33",
          "onSecondaryFixedVariant": "#104A73",
          "tertiaryFixed": "#E9DDFF",
          "tertiaryFixedDim": "#CFBDFE",
          "onTertiaryFixed": "#201047",
          "onTertiaryFixedVariant": "#4D3D75"
        },
        "dark": {
          "primary": "#97CBFF",
          "onPrimary": "#003354",
          "primaryContainer": "#004A77",
          "onPrimaryContainer": "#CEE5FF",
          "inversePrimary": "#00639C",
          "secondary": "#9CCBFB",
          "onSecondary": "#003354",
          "secondaryContainer": "#104A73",
          "onSecondaryContainer": "#CEE5FF",
          "tertiary": "#CFBDFE",
          "onTertiary": "#36275D",
          "tertiaryContainer": "#4D3D75",
          "onTertiaryContainer": "#E9DDFF",
          "background": "#15121C",
          "onBackground": "#E7E0EF",
          "surface": "#15121C",
          "onSurface": "#E7E0EF",
          "surfaceVariant": "#4A4458",
          "onSurfaceVariant": "#CBC2DB",
          "surfaceTint": "#97CBFF",
          "inverseSurface": "#E7E0EF",
          "inverseOnSurface": "#322F3A",
          "error": "#FFB4AB",
          "onError": "#690005",
          "errorContainer": "#93000A",
          "onErrorContainer": "#FFDAD6",
          "outline": "#958DA4",
          "outlineVariant": "#4A4458",
          "scrim": "#000000",
          "surfaceBright": "#3B3743",
          "surfaceContainer": "#211E28",
          "surfaceContainerHigh": "#2C2833",
          "surfaceContainerHighest": "#37333E",
          "surfaceContainerLow": "#1D1A24",
          "surfaceContainerLowest": "#0F0D16",
          "surfaceDim": "#15121C",
          "primaryFixed": "#CEE5FF",
          "primaryFixedDim": "#97CBFF",
          "onPrimaryFixed": "#001D33",
          "onPrimaryFixedVariant": "#004A77",
          "secondaryFixed": "#CEE5FF",
          "secondaryFixedDim": "#9CCBFB",
          "onSecondaryFixed": "#001D33",
          "onSecondaryFixedVariant": "#104A73",
          "tertiaryFixed": "#E9DDFF",
          "tertiaryFixedDim": "#CFBDFE",
          "onTertiaryFixed": "#201047",
          "onTertiaryFixedVariant": "#4D3D75"
        }
      }
    } as const);

export const lightColorScheme = { ...materialThemePresetSchemes.tonalSpot.light };

export const darkColorScheme = { ...materialThemePresetSchemes.tonalSpot.dark };

export type MaterialColorRole = (typeof materialColorSchemeRoles)[number];
export type MaterialThemePreset = (typeof materialThemePresets)[number];
export type MaterialThemeKeyColorRole = keyof (typeof materialThemePresetKeyColors)["tonalSpot"];
export type MaterialThemeKeyColors = {
  readonly [Role in MaterialThemeKeyColorRole]: string;
};
export type MaterialColorScheme = {
  readonly [Role in MaterialColorRole]: string;
};

export type MaterialColorSchemeInput = Partial<Record<MaterialColorRole, string>>;

export interface MaterialTheme {
  readonly dark: boolean;
  readonly preset: MaterialThemePreset;
  readonly sourceColor: string;
  readonly colorScheme: MaterialColorScheme;
}

export interface MaterialThemeOptions {
  readonly dark?: boolean;
  readonly preset?: MaterialThemePreset;
  readonly colorScheme?: MaterialColorSchemeInput;
}

export function getMaterialThemeColorScheme(
  preset: MaterialThemePreset,
  dark = false,
): MaterialColorScheme {
  return { ...materialThemePresetSchemes[preset][dark ? "dark" : "light"] };
}

export function getMaterialThemeKeyColors(
  preset: MaterialThemePreset,
): MaterialThemeKeyColors {
  return { ...materialThemePresetKeyColors[preset] };
}

function mergeMaterialColorScheme(
  base: MaterialColorScheme,
  overrides?: MaterialColorSchemeInput,
): MaterialColorScheme {
  const colorScheme: Record<MaterialColorRole, string> = { ...base };

  if (!overrides) {
    return colorScheme;
  }

  for (const role of materialColorSchemeRoles) {
    const value = overrides[role];

    if (value !== undefined) {
      colorScheme[role] = value;
    }
  }

  return colorScheme;
}

export function createMaterialTheme(options: MaterialThemeOptions = {}): MaterialTheme {
  const dark = options.dark ?? false;
  const preset = options.preset ?? "tonalSpot";
  const base = getMaterialThemeColorScheme(preset, dark);

  return {
    dark,
    preset,
    sourceColor: materialThemePresetSourceColors[preset],
    colorScheme: mergeMaterialColorScheme(base, options.colorScheme),
  };
}

export function getMaterialTheme(
  preset: MaterialThemePreset,
  options: Omit<MaterialThemeOptions, "preset"> = {},
): MaterialTheme {
  return createMaterialTheme({ ...options, preset });
}

export function getSchemeColor(
  colorScheme: MaterialColorScheme,
  role: MaterialColorRole,
): string {
  return colorScheme[role];
}
