// Generated from tokens/ by tools/codegen/generate.rb.
// Do not edit by hand.
@_exported import MaterialDesignColorCore
import SwiftUI

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public extension Color {
  init(materialColor: MaterialColor) {
    self.init(
      .sRGB,
      red: Double(materialColor.red) / 255.0,
      green: Double(materialColor.green) / 255.0,
      blue: Double(materialColor.blue) / 255.0,
      opacity: Double(materialColor.alpha) / 255.0
    )
  }

  static let red50 = Color(materialColor: MaterialPalette.red50)
  static let red100 = Color(materialColor: MaterialPalette.red100)
  static let red200 = Color(materialColor: MaterialPalette.red200)
  static let red300 = Color(materialColor: MaterialPalette.red300)
  static let red400 = Color(materialColor: MaterialPalette.red400)
  static let red500 = Color(materialColor: MaterialPalette.red500)
  static let red600 = Color(materialColor: MaterialPalette.red600)
  static let red700 = Color(materialColor: MaterialPalette.red700)
  static let red800 = Color(materialColor: MaterialPalette.red800)
  static let red900 = Color(materialColor: MaterialPalette.red900)
  static let redA100 = Color(materialColor: MaterialPalette.redA100)
  static let redA200 = Color(materialColor: MaterialPalette.redA200)
  static let redA400 = Color(materialColor: MaterialPalette.redA400)
  static let redA700 = Color(materialColor: MaterialPalette.redA700)
  static let pink50 = Color(materialColor: MaterialPalette.pink50)
  static let pink100 = Color(materialColor: MaterialPalette.pink100)
  static let pink200 = Color(materialColor: MaterialPalette.pink200)
  static let pink300 = Color(materialColor: MaterialPalette.pink300)
  static let pink400 = Color(materialColor: MaterialPalette.pink400)
  static let pink500 = Color(materialColor: MaterialPalette.pink500)
  static let pink600 = Color(materialColor: MaterialPalette.pink600)
  static let pink700 = Color(materialColor: MaterialPalette.pink700)
  static let pink800 = Color(materialColor: MaterialPalette.pink800)
  static let pink900 = Color(materialColor: MaterialPalette.pink900)
  static let pinkA100 = Color(materialColor: MaterialPalette.pinkA100)
  static let pinkA200 = Color(materialColor: MaterialPalette.pinkA200)
  static let pinkA400 = Color(materialColor: MaterialPalette.pinkA400)
  static let pinkA700 = Color(materialColor: MaterialPalette.pinkA700)
  static let purple50 = Color(materialColor: MaterialPalette.purple50)
  static let purple100 = Color(materialColor: MaterialPalette.purple100)
  static let purple200 = Color(materialColor: MaterialPalette.purple200)
  static let purple300 = Color(materialColor: MaterialPalette.purple300)
  static let purple400 = Color(materialColor: MaterialPalette.purple400)
  static let purple500 = Color(materialColor: MaterialPalette.purple500)
  static let purple600 = Color(materialColor: MaterialPalette.purple600)
  static let purple700 = Color(materialColor: MaterialPalette.purple700)
  static let purple800 = Color(materialColor: MaterialPalette.purple800)
  static let purple900 = Color(materialColor: MaterialPalette.purple900)
  static let purpleA100 = Color(materialColor: MaterialPalette.purpleA100)
  static let purpleA200 = Color(materialColor: MaterialPalette.purpleA200)
  static let purpleA400 = Color(materialColor: MaterialPalette.purpleA400)
  static let purpleA700 = Color(materialColor: MaterialPalette.purpleA700)
  static let deepPurple50 = Color(materialColor: MaterialPalette.deepPurple50)
  static let deepPurple100 = Color(materialColor: MaterialPalette.deepPurple100)
  static let deepPurple200 = Color(materialColor: MaterialPalette.deepPurple200)
  static let deepPurple300 = Color(materialColor: MaterialPalette.deepPurple300)
  static let deepPurple400 = Color(materialColor: MaterialPalette.deepPurple400)
  static let deepPurple500 = Color(materialColor: MaterialPalette.deepPurple500)
  static let deepPurple600 = Color(materialColor: MaterialPalette.deepPurple600)
  static let deepPurple700 = Color(materialColor: MaterialPalette.deepPurple700)
  static let deepPurple800 = Color(materialColor: MaterialPalette.deepPurple800)
  static let deepPurple900 = Color(materialColor: MaterialPalette.deepPurple900)
  static let deepPurpleA100 = Color(materialColor: MaterialPalette.deepPurpleA100)
  static let deepPurpleA200 = Color(materialColor: MaterialPalette.deepPurpleA200)
  static let deepPurpleA400 = Color(materialColor: MaterialPalette.deepPurpleA400)
  static let deepPurpleA700 = Color(materialColor: MaterialPalette.deepPurpleA700)
  static let indigo50 = Color(materialColor: MaterialPalette.indigo50)
  static let indigo100 = Color(materialColor: MaterialPalette.indigo100)
  static let indigo200 = Color(materialColor: MaterialPalette.indigo200)
  static let indigo300 = Color(materialColor: MaterialPalette.indigo300)
  static let indigo400 = Color(materialColor: MaterialPalette.indigo400)
  static let indigo500 = Color(materialColor: MaterialPalette.indigo500)
  static let indigo600 = Color(materialColor: MaterialPalette.indigo600)
  static let indigo700 = Color(materialColor: MaterialPalette.indigo700)
  static let indigo800 = Color(materialColor: MaterialPalette.indigo800)
  static let indigo900 = Color(materialColor: MaterialPalette.indigo900)
  static let indigoA100 = Color(materialColor: MaterialPalette.indigoA100)
  static let indigoA200 = Color(materialColor: MaterialPalette.indigoA200)
  static let indigoA400 = Color(materialColor: MaterialPalette.indigoA400)
  static let indigoA700 = Color(materialColor: MaterialPalette.indigoA700)
  static let blue50 = Color(materialColor: MaterialPalette.blue50)
  static let blue100 = Color(materialColor: MaterialPalette.blue100)
  static let blue200 = Color(materialColor: MaterialPalette.blue200)
  static let blue300 = Color(materialColor: MaterialPalette.blue300)
  static let blue400 = Color(materialColor: MaterialPalette.blue400)
  static let blue500 = Color(materialColor: MaterialPalette.blue500)
  static let blue600 = Color(materialColor: MaterialPalette.blue600)
  static let blue700 = Color(materialColor: MaterialPalette.blue700)
  static let blue800 = Color(materialColor: MaterialPalette.blue800)
  static let blue900 = Color(materialColor: MaterialPalette.blue900)
  static let blueA100 = Color(materialColor: MaterialPalette.blueA100)
  static let blueA200 = Color(materialColor: MaterialPalette.blueA200)
  static let blueA400 = Color(materialColor: MaterialPalette.blueA400)
  static let blueA700 = Color(materialColor: MaterialPalette.blueA700)
  static let lightBlue50 = Color(materialColor: MaterialPalette.lightBlue50)
  static let lightBlue100 = Color(materialColor: MaterialPalette.lightBlue100)
  static let lightBlue200 = Color(materialColor: MaterialPalette.lightBlue200)
  static let lightBlue300 = Color(materialColor: MaterialPalette.lightBlue300)
  static let lightBlue400 = Color(materialColor: MaterialPalette.lightBlue400)
  static let lightBlue500 = Color(materialColor: MaterialPalette.lightBlue500)
  static let lightBlue600 = Color(materialColor: MaterialPalette.lightBlue600)
  static let lightBlue700 = Color(materialColor: MaterialPalette.lightBlue700)
  static let lightBlue800 = Color(materialColor: MaterialPalette.lightBlue800)
  static let lightBlue900 = Color(materialColor: MaterialPalette.lightBlue900)
  static let lightBlueA100 = Color(materialColor: MaterialPalette.lightBlueA100)
  static let lightBlueA200 = Color(materialColor: MaterialPalette.lightBlueA200)
  static let lightBlueA400 = Color(materialColor: MaterialPalette.lightBlueA400)
  static let lightBlueA700 = Color(materialColor: MaterialPalette.lightBlueA700)
  static let cyan50 = Color(materialColor: MaterialPalette.cyan50)
  static let cyan100 = Color(materialColor: MaterialPalette.cyan100)
  static let cyan200 = Color(materialColor: MaterialPalette.cyan200)
  static let cyan300 = Color(materialColor: MaterialPalette.cyan300)
  static let cyan400 = Color(materialColor: MaterialPalette.cyan400)
  static let cyan500 = Color(materialColor: MaterialPalette.cyan500)
  static let cyan600 = Color(materialColor: MaterialPalette.cyan600)
  static let cyan700 = Color(materialColor: MaterialPalette.cyan700)
  static let cyan800 = Color(materialColor: MaterialPalette.cyan800)
  static let cyan900 = Color(materialColor: MaterialPalette.cyan900)
  static let cyanA100 = Color(materialColor: MaterialPalette.cyanA100)
  static let cyanA200 = Color(materialColor: MaterialPalette.cyanA200)
  static let cyanA400 = Color(materialColor: MaterialPalette.cyanA400)
  static let cyanA700 = Color(materialColor: MaterialPalette.cyanA700)
  static let teal50 = Color(materialColor: MaterialPalette.teal50)
  static let teal100 = Color(materialColor: MaterialPalette.teal100)
  static let teal200 = Color(materialColor: MaterialPalette.teal200)
  static let teal300 = Color(materialColor: MaterialPalette.teal300)
  static let teal400 = Color(materialColor: MaterialPalette.teal400)
  static let teal500 = Color(materialColor: MaterialPalette.teal500)
  static let teal600 = Color(materialColor: MaterialPalette.teal600)
  static let teal700 = Color(materialColor: MaterialPalette.teal700)
  static let teal800 = Color(materialColor: MaterialPalette.teal800)
  static let teal900 = Color(materialColor: MaterialPalette.teal900)
  static let tealA100 = Color(materialColor: MaterialPalette.tealA100)
  static let tealA200 = Color(materialColor: MaterialPalette.tealA200)
  static let tealA400 = Color(materialColor: MaterialPalette.tealA400)
  static let tealA700 = Color(materialColor: MaterialPalette.tealA700)
  static let green50 = Color(materialColor: MaterialPalette.green50)
  static let green100 = Color(materialColor: MaterialPalette.green100)
  static let green200 = Color(materialColor: MaterialPalette.green200)
  static let green300 = Color(materialColor: MaterialPalette.green300)
  static let green400 = Color(materialColor: MaterialPalette.green400)
  static let green500 = Color(materialColor: MaterialPalette.green500)
  static let green600 = Color(materialColor: MaterialPalette.green600)
  static let green700 = Color(materialColor: MaterialPalette.green700)
  static let green800 = Color(materialColor: MaterialPalette.green800)
  static let green900 = Color(materialColor: MaterialPalette.green900)
  static let greenA100 = Color(materialColor: MaterialPalette.greenA100)
  static let greenA200 = Color(materialColor: MaterialPalette.greenA200)
  static let greenA400 = Color(materialColor: MaterialPalette.greenA400)
  static let greenA700 = Color(materialColor: MaterialPalette.greenA700)
  static let lightGreen50 = Color(materialColor: MaterialPalette.lightGreen50)
  static let lightGreen100 = Color(materialColor: MaterialPalette.lightGreen100)
  static let lightGreen200 = Color(materialColor: MaterialPalette.lightGreen200)
  static let lightGreen300 = Color(materialColor: MaterialPalette.lightGreen300)
  static let lightGreen400 = Color(materialColor: MaterialPalette.lightGreen400)
  static let lightGreen500 = Color(materialColor: MaterialPalette.lightGreen500)
  static let lightGreen600 = Color(materialColor: MaterialPalette.lightGreen600)
  static let lightGreen700 = Color(materialColor: MaterialPalette.lightGreen700)
  static let lightGreen800 = Color(materialColor: MaterialPalette.lightGreen800)
  static let lightGreen900 = Color(materialColor: MaterialPalette.lightGreen900)
  static let lightGreenA100 = Color(materialColor: MaterialPalette.lightGreenA100)
  static let lightGreenA200 = Color(materialColor: MaterialPalette.lightGreenA200)
  static let lightGreenA400 = Color(materialColor: MaterialPalette.lightGreenA400)
  static let lightGreenA700 = Color(materialColor: MaterialPalette.lightGreenA700)
  static let lime50 = Color(materialColor: MaterialPalette.lime50)
  static let lime100 = Color(materialColor: MaterialPalette.lime100)
  static let lime200 = Color(materialColor: MaterialPalette.lime200)
  static let lime300 = Color(materialColor: MaterialPalette.lime300)
  static let lime400 = Color(materialColor: MaterialPalette.lime400)
  static let lime500 = Color(materialColor: MaterialPalette.lime500)
  static let lime600 = Color(materialColor: MaterialPalette.lime600)
  static let lime700 = Color(materialColor: MaterialPalette.lime700)
  static let lime800 = Color(materialColor: MaterialPalette.lime800)
  static let lime900 = Color(materialColor: MaterialPalette.lime900)
  static let limeA100 = Color(materialColor: MaterialPalette.limeA100)
  static let limeA200 = Color(materialColor: MaterialPalette.limeA200)
  static let limeA400 = Color(materialColor: MaterialPalette.limeA400)
  static let limeA700 = Color(materialColor: MaterialPalette.limeA700)
  static let yellow50 = Color(materialColor: MaterialPalette.yellow50)
  static let yellow100 = Color(materialColor: MaterialPalette.yellow100)
  static let yellow200 = Color(materialColor: MaterialPalette.yellow200)
  static let yellow300 = Color(materialColor: MaterialPalette.yellow300)
  static let yellow400 = Color(materialColor: MaterialPalette.yellow400)
  static let yellow500 = Color(materialColor: MaterialPalette.yellow500)
  static let yellow600 = Color(materialColor: MaterialPalette.yellow600)
  static let yellow700 = Color(materialColor: MaterialPalette.yellow700)
  static let yellow800 = Color(materialColor: MaterialPalette.yellow800)
  static let yellow900 = Color(materialColor: MaterialPalette.yellow900)
  static let yellowA100 = Color(materialColor: MaterialPalette.yellowA100)
  static let yellowA200 = Color(materialColor: MaterialPalette.yellowA200)
  static let yellowA400 = Color(materialColor: MaterialPalette.yellowA400)
  static let yellowA700 = Color(materialColor: MaterialPalette.yellowA700)
  static let amber50 = Color(materialColor: MaterialPalette.amber50)
  static let amber100 = Color(materialColor: MaterialPalette.amber100)
  static let amber200 = Color(materialColor: MaterialPalette.amber200)
  static let amber300 = Color(materialColor: MaterialPalette.amber300)
  static let amber400 = Color(materialColor: MaterialPalette.amber400)
  static let amber500 = Color(materialColor: MaterialPalette.amber500)
  static let amber600 = Color(materialColor: MaterialPalette.amber600)
  static let amber700 = Color(materialColor: MaterialPalette.amber700)
  static let amber800 = Color(materialColor: MaterialPalette.amber800)
  static let amber900 = Color(materialColor: MaterialPalette.amber900)
  static let amberA100 = Color(materialColor: MaterialPalette.amberA100)
  static let amberA200 = Color(materialColor: MaterialPalette.amberA200)
  static let amberA400 = Color(materialColor: MaterialPalette.amberA400)
  static let amberA700 = Color(materialColor: MaterialPalette.amberA700)
  static let orange50 = Color(materialColor: MaterialPalette.orange50)
  static let orange100 = Color(materialColor: MaterialPalette.orange100)
  static let orange200 = Color(materialColor: MaterialPalette.orange200)
  static let orange300 = Color(materialColor: MaterialPalette.orange300)
  static let orange400 = Color(materialColor: MaterialPalette.orange400)
  static let orange500 = Color(materialColor: MaterialPalette.orange500)
  static let orange600 = Color(materialColor: MaterialPalette.orange600)
  static let orange700 = Color(materialColor: MaterialPalette.orange700)
  static let orange800 = Color(materialColor: MaterialPalette.orange800)
  static let orange900 = Color(materialColor: MaterialPalette.orange900)
  static let orangeA100 = Color(materialColor: MaterialPalette.orangeA100)
  static let orangeA200 = Color(materialColor: MaterialPalette.orangeA200)
  static let orangeA400 = Color(materialColor: MaterialPalette.orangeA400)
  static let orangeA700 = Color(materialColor: MaterialPalette.orangeA700)
  static let deepOrange50 = Color(materialColor: MaterialPalette.deepOrange50)
  static let deepOrange100 = Color(materialColor: MaterialPalette.deepOrange100)
  static let deepOrange200 = Color(materialColor: MaterialPalette.deepOrange200)
  static let deepOrange300 = Color(materialColor: MaterialPalette.deepOrange300)
  static let deepOrange400 = Color(materialColor: MaterialPalette.deepOrange400)
  static let deepOrange500 = Color(materialColor: MaterialPalette.deepOrange500)
  static let deepOrange600 = Color(materialColor: MaterialPalette.deepOrange600)
  static let deepOrange700 = Color(materialColor: MaterialPalette.deepOrange700)
  static let deepOrange800 = Color(materialColor: MaterialPalette.deepOrange800)
  static let deepOrange900 = Color(materialColor: MaterialPalette.deepOrange900)
  static let deepOrangeA100 = Color(materialColor: MaterialPalette.deepOrangeA100)
  static let deepOrangeA200 = Color(materialColor: MaterialPalette.deepOrangeA200)
  static let deepOrangeA400 = Color(materialColor: MaterialPalette.deepOrangeA400)
  static let deepOrangeA700 = Color(materialColor: MaterialPalette.deepOrangeA700)
  static let brown50 = Color(materialColor: MaterialPalette.brown50)
  static let brown100 = Color(materialColor: MaterialPalette.brown100)
  static let brown200 = Color(materialColor: MaterialPalette.brown200)
  static let brown300 = Color(materialColor: MaterialPalette.brown300)
  static let brown400 = Color(materialColor: MaterialPalette.brown400)
  static let brown500 = Color(materialColor: MaterialPalette.brown500)
  static let brown600 = Color(materialColor: MaterialPalette.brown600)
  static let brown700 = Color(materialColor: MaterialPalette.brown700)
  static let brown800 = Color(materialColor: MaterialPalette.brown800)
  static let brown900 = Color(materialColor: MaterialPalette.brown900)
  static let grey50 = Color(materialColor: MaterialPalette.grey50)
  static let grey100 = Color(materialColor: MaterialPalette.grey100)
  static let grey200 = Color(materialColor: MaterialPalette.grey200)
  static let grey300 = Color(materialColor: MaterialPalette.grey300)
  static let grey400 = Color(materialColor: MaterialPalette.grey400)
  static let grey500 = Color(materialColor: MaterialPalette.grey500)
  static let grey600 = Color(materialColor: MaterialPalette.grey600)
  static let grey700 = Color(materialColor: MaterialPalette.grey700)
  static let grey800 = Color(materialColor: MaterialPalette.grey800)
  static let grey900 = Color(materialColor: MaterialPalette.grey900)
  static let blueGrey50 = Color(materialColor: MaterialPalette.blueGrey50)
  static let blueGrey100 = Color(materialColor: MaterialPalette.blueGrey100)
  static let blueGrey200 = Color(materialColor: MaterialPalette.blueGrey200)
  static let blueGrey300 = Color(materialColor: MaterialPalette.blueGrey300)
  static let blueGrey400 = Color(materialColor: MaterialPalette.blueGrey400)
  static let blueGrey500 = Color(materialColor: MaterialPalette.blueGrey500)
  static let blueGrey600 = Color(materialColor: MaterialPalette.blueGrey600)
  static let blueGrey700 = Color(materialColor: MaterialPalette.blueGrey700)
  static let blueGrey800 = Color(materialColor: MaterialPalette.blueGrey800)
  static let blueGrey900 = Color(materialColor: MaterialPalette.blueGrey900)
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public extension MaterialColor {
  var color: Color {
    Color(materialColor: self)
  }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
private struct MaterialThemeEnvironmentKey: EnvironmentKey {
  static let defaultValue = MaterialTheme.light
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public extension EnvironmentValues {
  var materialTheme: MaterialTheme {
    get { self[MaterialThemeEnvironmentKey.self] }
    set { self[MaterialThemeEnvironmentKey.self] = newValue }
  }
}

@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public extension View {
  func materialTheme(_ theme: MaterialTheme) -> some View {
    environment(\.materialTheme, theme)
  }
}
